import * as Immutable from 'immutable';

export enum MessageType {
    ERROR,
    WARNING,
    INFO,
    SUCCESS
}

export interface Message {
    id: number;
    type: MessageType;

    header: string;
    body?: string | string[];

    dismissible?: boolean;
    expandable?: boolean;
}

export enum ErrorResponseType {
    PARSE,
    COMPILATION,
    OTHER
}

export type ErrorResponse = ParserErrorResponse | CompilationErrorResponse | OtherErrorResponse;

interface BaseErrorResponse {
    messageId?: number;

    type: ErrorResponseType;
    message: string;
}

export interface ParserErrorResponse extends BaseErrorResponse {
    type: ErrorResponseType.PARSE;

    errorMessages: string[];
}

export interface CompilationErrorResponse extends BaseErrorResponse {
    type: ErrorResponseType.COMPILATION;

    startPos: number;
    lineNum: number;
    startPosInLine: number;
    endPos: number;
}

export interface OtherErrorResponse extends BaseErrorResponse {
    type: ErrorResponseType.OTHER
}

export interface Song {
    length: number;
    data: string;
}

export enum MusicPlayerState {
    STOPPED,
    LOADING,
    PLAYING
}

export enum CodeState {
    NOT_COMPILED,
    COMPILED,
    COMPILING,
    ERROR
}

export interface PlayerState {
    musicPlayerState: MusicPlayerState;
    codeState: CodeState;
    song?: Song;
}

export interface EditorState {
    nextMessageID: number;
    messages: Immutable.Map<number, Message>;
    errors: Immutable.List<ErrorResponse>;
    player: PlayerState;
}

export const DEFAULT_EDITOR_STATE: EditorState = {
    nextMessageID: 1,
    messages: Immutable.Map.of(
        0, {
            id: 0,
            type: MessageType.INFO,
            header: "Click compile to compile",
            body: ['More content', 'and more'],

            dismissible: true,
            expandable: true
        } as Message
    ),
    errors: Immutable.List.of<ErrorResponse>(
        {
            messageId: null,
            type: ErrorResponseType.COMPILATION,
            message: 'Error during compilation',
            startPos: 0,
            lineNum: 0,
            startPosInLine: 0,
            endPos: 0
        }
    ),
    player: {
        musicPlayerState: MusicPlayerState.STOPPED,
        codeState: CodeState.COMPILED,
        song: {
            length: 42,
            data: 'TVRoZAAAAAYAAQAGA8BNVHJrAAAAEwD/WAQEAhgIAP9RAwehIAD/LwBNVHJrAAAD/gCQKzWeAIArYACQLzWeAIAvYACQKDWeAIAoYACQMDWeAIAwYACQKzWHQIArYACQKzWHQIArYACQKzWHQIArYACQKzWHQIArYACQLzWHQIAvYACQLzWHQIAvYACQLzWHQIAvYACQLzWHQIAvYACQKDWHQIAoYACQKDWHQIAoYACQKDWHQIAoYACQKDWHQIAoYACQMDWHQIAwYACQMDWHQIAwYACQMDWHQIAwYACQMDWHQIAwYACQHzUAKzWHQIAfYAArYACQHzUAKzWHQIAfYAArYACQHzUAKzWHQIAfYAArYACQHzUAKzWHQIAfYAArYACQIzUALzWHQIAjYAAvYACQIzUALzWHQIAjYAAvYACQIzUALzWHQIAjYAAvYACQIzUALzWHQIAjYAAvYACQHDUAKDWHQIAcYAAoYACQHDUAKDWHQIAcYAAoYACQHDUAKDWHQIAcYAAoYACQHDUAKDWHQIAcYAAoYACQJDUAMDWHQIAkYAAwYACQJDUAMDWHQIAkYAAwYACQJDUAMDWHQIAkYAAwYACQJDUAMDWHQIAkYAAwYACQHzWDYIAfYACQGjWDYIAaYACQKzWDYIArYACQGjWDYIAaYACQKzWDYIArYACQGjWDYIAaYACQKzWDYIArYACQGjWDYIAaYACQIzWDYIAjYACQHjWDYIAeYACQLzWDYIAvYACQHjWDYIAeYACQLzWDYIAvYACQHjWDYIAeYACQLzWDYIAvYACQHjWDYIAeYACQHDWDYIAcYACQIzWDYIAjYACQKDWDYIAoYACQIzWDYIAjYACQKDWDYIAoYACQIzWDYIAjYACQKDWDYIAoYACQIzWDYIAjYACQJDWDYIAkYACQKzWDYIArYACQMDWDYIAwYACQKzWDYIArYACQMDWDYIAwYACQKzWDYIArYACQMDWDYIAwYACQKzWDYIArYACQHzWDYIAfYACQGjWDYIAaYACQKzWDYIArYACQGjWDYIAaYACQKzWDYIArYACQGjWDYIAaYACQKzWDYIArYACQGjWDYIAaYACQIzWDYIAjYACQHjWDYIAeYACQLzWDYIAvYACQHjWDYIAeYACQLzWDYIAvYACQHjWDYIAeYACQLzWDYIAvYACQHjWDYIAeYACQHDWDYIAcYACQIzWDYIAjYACQKDWDYIAoYACQIzWDYIAjYACQKDWDYIAoYACQIzWDYIAjYACQKDWDYIAoYACQIzWDYIAjYACQJDWDYIAkYACQKzWDYIArYACQMDWDYIAwYACQKzWDYIArYACQMDWDYIAwYACQKzWDYIArYACQMDWDYIAwYACQKzWDYIArYACQHzUAJjUAKzWeAIAfYAAmYAArYIdA/y8ATVRyawAABW0AkUc1AEo1g2CBR2AASmAAkUM1g2CBQ2AAkUc1AEo1jwCBR2AASmAAkUc1AEo1g2CBR2AASmAAkUM1g2CBQ2AAkUc1AEo1g2CBR2AASmAAkUI1g2CBQmAAkUc1AEo1jwCBR2AASmAAkUc1AEo1g2CBR2AASmAAkUI1g2CBQmAAkUc1AEw1g2CBR2AATGAAkUM1g2CBQ2AAkUc1AEw1jwCBR2AATGAAkUc1AEw1g2CBR2AATGAAkUM1g2CBQ2AAkUg1AEw1h0CBSGAATGAAkUg1AEw1h0CBSGAATGAAkUg1AEw1g2CBSGAATGAAkUc1g2CBR2AAkUU1g2CBRWAAkUc1g2CBR2AAkUc1AEo1g2CBR2AASmAAkUM1g2CBQ2AAkUc1AEo1jwCBR2AASmAAkUc1AEo1g2CBR2AASmAAkUM1g2CBQ2AAkUc1AEo1g2CBR2AASmAAkUI1g2CBQmAAkUc1AEo1jwCBR2AASmAAkUc1AEo1g2CBR2AASmAAkUI1g2CBQmAAkUc1AEw1g2CBR2AATGAAkUM1g2CBQ2AAkUc1AEw1jwCBR2AATGAAkUc1AEw1g2CBR2AATGAAkUM1g2CBQ2AAkUg1AEw1h0CBSGAATGAAkUg1AEw1h0CBSGAATGAAkUg1AEw1g2CBSGAATGAAkUc1g2CBR2AAkUU1g2CBRWAAkUc1g2CBR2AAkUc1AEo1g2CBR2AASmAAkUM1g2CBQ2AAkUc1AEo1jwCBR2AASmAAkUc1AEo1g2CBR2AASmAAkUM1g2CBQ2AAkUc1AEo1g2CBR2AASmAAkUI1g2CBQmAAkUc1AEo1jwCBR2AASmAAkUc1AEo1g2CBR2AASmAAkUI1g2CBQmAAkUc1AEw1g2CBR2AATGAAkUM1g2CBQ2AAkUc1AEw1jwCBR2AATGAAkUc1AEw1g2CBR2AATGAAkUM1g2CBQ2AAkUg1AEw1h0CBSGAATGAAkUg1AEw1h0CBSGAATGAAkUg1AEw1g2CBSGAATGAAkUc1g2CBR2AAkUU1g2CBRWAAkUc1g2CBR2AAkUc1AEo1g2CBR2AASmAAkUM1g2CBQ2AAkUc1AEo1jwCBR2AASmAAkUc1AEo1g2CBR2AASmAAkUM1g2CBQ2AAkUc1AEo1g2CBR2AASmAAkUI1g2CBQmAAkUc1AEo1jwCBR2AASmAAkUc1AEo1g2CBR2AASmAAkUI1g2CBQmAAkUc1AEw1g2CBR2AATGAAkUM1g2CBQ2AAkUc1AEw1jwCBR2AATGAAkUc1AEw1g2CBR2AATGAAkUM1g2CBQ2AAkUg1AEw1h0CBSGAATGAAkUg1AEw1h0CBSGAATGAAkUg1AEw1g2CBSGAATGAAkUc1g2CBR2AAkUU1g2CBRWAAkUc1g2CBR2AAkUc1AEo1g2CBR2AASmAAkUM1g2CBQ2AAkUc1AEo1jwCBR2AASmAAkUc1AEo1g2CBR2AASmAAkUM1g2CBQ2AAkUc1AEo1g2CBR2AASmAAkUI1g2CBQmAAkUc1AEo1jwCBR2AASmAAkUc1AEo1g2CBR2AASmAAkUI1g2CBQmAAkUc1AEw1g2CBR2AATGAAkUM1g2CBQ2AAkUc1AEw1jwCBR2AATGAAkUc1AEw1g2CBR2AATGAAkUM1g2CBQ2AAkUg1AEw1h0CBSGAATGAAkUg1AEw1h0CBSGAATGAAkUg1AEw1g2CBSGAATGAAkUc1g2CBR2AAkUU1g2CBRWAAkUc1g2CBR2AAsUB/AJFDNYJAPjWCQIE+YACRQySCQEc1gkBDJIJAgUNgAJFHJIJASjWCQEckgkCBR2AAkUokgkCBSmAAsUAAAJFDNXhPNYZIgUNgAE9gh0D/LwBNVHJrAAAA/gDCFgCyeACBhwCCQ2CeAE9ghBxOAYNgTwGDYE4Bg2BKAZ1ETGCHQEhgh0BIYIQcSAGDYEcBg2BFAYNgRwGORENgngBPYINgTmCEHE8Bg2BRAYNgTgGORExghBxKAYNgTAGDYEoBg2BHAYcESGCHQEhghBxIAYNgRwGDYEUBgyRHYI8AQ2CeAE9ghBxOAYNgTwGDYE4Bg2BKAZ1ETGCHQEhgh0BIYIQcSAGDYEcBg2BFAYNgRwGORENgngBPYINgTmCEHE8Bg2BRAYNgTgGORExghBxKAYNgTAGDYEoBg2BHAYcESGCHQEhghBxIAYNgRwGDYEUBgyRHYIdA/y8ATVRyawAAAXYAwx4As3gAgtFAgzxgAENgAEhgh0A8YABDYABIYIdAPGAAQ2AASGCHQDxgAENgAEhgh0A3YAAyYABDYIdAN2AAMmAAQ2CHQDdgADJgAENgh0A3YAAyYABDYIdAO2AANmAAR2CHQDtgADZgAEdgh0A7YAA2YABHYIdAO2AANmAAR2CHQDRgADtgAEBgh0A0YAA7YABAYIdANGAAO2AAQGCHQDRgADtgAEBgh0A8YABDYABIYIdAPGAAQ2AASGCHQDxgAENgAEhgh0A8YABDYABIYIdAN2AAMmAAQ2CHQDdgADJgAENgh0A3YAAyYABDYIdAN2AAMmAAQ2CHQDtgADZgAEdgh0A7YAA2YABHYIdAO2AANmAAR2CHQDtgADZgAEdgh0A0YAA7YABAYIdANGAAO2AAQGCHQDRgADtgAEBgh0A0YAA7YABAYIdAPGAAQ2AASGCHQDxgAENgAEhgh0A8YABDYABIYIdAPGAAQ2AASGCHQP8vAE1UcmsAAARvALlbKPgAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmSQqACYqh0CJJGAAJmAAmTEqADkqh0CJMWAAOWAAmSQqg2CJJGAAmSQqg2CJJGAAmSYqgXCJJmAAmSYqgXCJJmAAmSYqgXCJJmAAmSYqgXCJJmAAmSQqADkqh0CJJGAAOWAAmTkqACYqh0CJOWAAJmAAmSQqADkqg2CJJGAAOWAAmSQqg2CJJGAAmTkqACYqh0CJOWAAJmAAmSQqADkqh0CJJGAAOWAAmTkqACYqh0CJOWAAJmAAmSQqADkqg2CJJGAAOWAAmSQqg2CJJGAAmTkqACYqh0CJOWAAJmAAmSQqADkqh0CJJGAAOWAAmTkqACYqh0CJOWAAJmAAmSQqADkqg2CJJGAAOWAAmSQqg2CJJGAAmTkqACYqh0CJOWAAJmAAmSQqADkqh0CJJGAAOWAAmTkqACYqh0CJOWAAJmAAmSQqADkqg2CJJGAAOWAAmSQqg2CJJGAAmTkqACYqgXCJOWAAJmAAmSYqgXCJJmAAmSYqgXCJJmAAmSYqgXCJJmAAmSQqADkqh0CJJGAAOWAAmTkqACYqh0CJOWAAJmAAmSQqADkqg2CJJGAAOWAAmSQqg2CJJGAAmTkqACYqh0CJOWAAJmAAmSQqADkqh0CJJGAAOWAAmTkqACYqh0CJOWAAJmAAmSQqADkqg2CJJGAAOWAAmSQqg2CJJGAAmTkqACYqh0CJOWAAJmAAmSQqADkqh0CJJGAAOWAAmTkqACYqh0CJOWAAJmAAmSQqADkqg2CJJGAAOWAAmSQqg2CJJGAAmTkqACYqh0CJOWAAJmAAmSQqADkqh0CJJGAAOWAAmTkqACYqh0CJOWAAJmAAmSQqADkqg2CJJGAAOWAAmSQqg2CJJGAAmTkqACYqgXCJOWAAJmAAmSYqgXCJJmAAmSYqgXCJJmAAmSYqgXCJJmAAmTEqADkqngCJMWAAOWCHQP8v'
        }
    }
};
